# Generated by Django 4.1.1 on 2022-11-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealhunter', '0002_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='d_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
