# Generated by Django 4.1.1 on 2022-11-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealhunter', '0003_alter_deal_d_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='deal',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
